id: P71B4496F
initial_creation_type: input
source_metadata:
  title: Kachöpa Series
  language: bo
  description: Prayers and Practices
  volume:
    dc9e6271dcc6469eb10f716fd9dbcf6c:
      title: Raising the Windhorse
      parent: Prayers and Practices
created_at: '2022-03-01T00:09:28.226844'
last_modified_at: '2022-03-01T00:09:28.226847'
statistics:
  total_words: 69
  total_non_words: 4
quality:
  non_words_ratio: 0.06
